version: '3'

services:
  mysql:
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3301:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_HOST: localhost
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  test_mysql:
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: "${COMPOSE_PROJECT_NAME}_test_mysql"
    restart: unless-stopped
    volumes:
      - test_database:/var/lib/mysql
    ports:
      - "3302:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_TEST_DATABASE}"
      MYSQL_HOST: localhost
      MYSQL_USER: "${MYSQL_TEST_USER}"
      MYSQL_PASSWORD: "${MYSQL_TEST_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_TEST_ROOT_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  redis:
    image: redis:latest
    container_name: app_redis
    ports:
      - "6382:6379"

  php-fpm:
    build:
      context: ../src/
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    volumes:
    - ../src/public:/var/www/public
volumes:
  database:
  test_database:
